version: '2'
services:
  wifi-connect:
    build: ./wifi-connect
    privileged: true
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
  ssb-server:
    build: ./ssb-server
    network_mode: "host"
    volumes:
      - ssbhome:/root/.ssb
  yggdrasil:
    build: ./yggdrasil
    privileged: true

volumes:
  ssbhome:
