version: '2.1'
services:
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
  ssb-server:
    build: ./ssb-server
    network_mode: "host"
    volumes:
      - ssbhome:/root/.ssb
  # yggdrasil:
  #   build: ./yggdrasil
  #   privileged: true

volumes:
  ssbhome:
